---
title: "FischersExactTest"
format: pdf
editor: visual
---

```{r}
fit <- fit_MIMOSA(sim_data)
ROC_results <- function(fit, n_samples) {

  # Single iteration version (i = 1)
  stat <- fdr(fit[[1]])
  truth <- gl(2, n_samples/2) %in% 2
  th <- seq(0, 1, l = 1000)
  tpr <- sapply(th, function(x){
    sum((stat <= x)[truth])
  })

  tpr <- tpr / sum(truth)
  fpr <- sapply(th, function(x){
    sum((stat <= x)[!truth])
  })
  fpr <- fpr / sum(!truth)
  ROC <- data.frame(TPR = tpr, FPR = fpr, Ntot = names(fit)[1])

  # Return plot for ROC curve
  p <- ggplot(ROC) + geom_line(aes(x = FPR, y = TPR, color = Ntot), lwd = 1.5) + theme_bw()
  
  return(p)
} 

#We can compare MIMOSA to Fishers exact test 
ROC.fisher<-function(fit, n_samples){
  p<-vector('numeric',n_samples)
  for(i in 1:100){
    # Single iteration version (i = 1)
    p[i]<-fisher.test(matrix(countsTable(fit[[1]])[i,],nrow=2,byrow=FALSE),alternative="less")$p
  }
  p<-p.adjust(p,"fdr")
   truth<-gl(2,n_samples/2)%in%2
  th<-seq(0,1,l=1000)
  tpr<-sapply(th,function(x){
      sum((p<=x)[truth])
  })/sum(truth)
    fpr<-sapply(th,function(x){
      sum((p<=x)[!truth])
  })/sum(!truth)
  data.frame(TPR=tpr,FPR=fpr,Ntot=names(fit)[1])
  }
ROC<-cbind(rbind(ROC,ROC.fisher),Method=gl(2,3000,labels=c("MIMOSA","Fisher")))
ggplot(ROC)+geom_line(aes(x=FPR,y=TPR,color=Method),lwd=1.5)+facet_wrap(~Ntot)+theme_bw()





```

You can add options to executable code like this

```{r}

```
